module.exports = {
  extends: [
    'eslint-config-airbnb-base'
  ].map(require.resolve),
  "env": {
    "browser": true,
    "node": false,
    "es6": false,
    "commonjs": false,
    "jquery": true
  },
  rules: {
    "indent": ["error", 4],
    "func-names": "off",
    "vars-on-top": "off",
    "no-use-before-define": ["error", { "functions": false, "classes": true }],
    "no-param-reassign": ["error", {"props":  false}],
    "no-plusplus": ["error", { "allowForLoopAfterthoughts": true }],
    "strict": ["error", "global"],
    "arrow-body-style": "off",
    "arrow-parens": "off",
    "arrow-spacing": "off",
    "constructor-super": "off",
    "generator-star-spacing": "off",
    "no-class-assign": "off",
    "no-confusing-arrow": "off",
    "no-const-assign": "off",
    "no-dupe-class-members": "off",
    "no-duplicate-imports": "error",
    "no-new-symbol": "off",
    "no-restricted-imports": "off",
    "no-this-before-super": "off",
    "no-useless-computed-key": "off",
    "no-useless-constructor": "off",
    "no-useless-rename": "off",
    "no-var": "off",
    "object-shorthand": "off",
    "prefer-arrow-callback": "off",
    "prefer-const": "off",
    "prefer-destructuring": "off",
    "prefer-numeric-literals": "off",
    "prefer-reflect": "off",
    "prefer-rest-params": "off",
    "prefer-spread": "off",
    "prefer-template": "off",
    "require-yield": "off",
    "rest-spread-spacing": "off",
    "symbol-description": "off",
    "template-curly-spacing": "off",
    "yield-star-spacing": "off",
    "max-len": [2, {"code": 120, "tabWidth": 2, "ignoreUrls": true}]
  }
};
